version: '3'
services:
  ddc-node-0:
    container_name: 'ddc-node-0'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8080'
      - 'REMOTE_HTTP_ADDR=http://localhost:8080'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-0/tcp/5000'
      - 'P2P_WHITELIST=12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8080:8080'
    volumes:
      - ./node-0-p2p-config.json:/config/p2p.json
  ddc-node-1:
    container_name: 'ddc-node-1'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8081'
      - 'REMOTE_HTTP_ADDR=http://localhost:8081'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-1/tcp/5001'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8081:8081'
    volumes:
      - ./node-1-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
  ddc-node-2:
    container_name: 'ddc-node-2'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8082'
      - 'REMOTE_HTTP_ADDR=http://localhost:8082'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-2/tcp/5002'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8082:8082'
    volumes:
      - ./node-2-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
  ddc-node-3:
    container_name: 'ddc-node-3'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8083'
      - 'REMOTE_HTTP_ADDR=http://localhost:8083'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-3/tcp/5003'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8083:8083'
    volumes:
      - ./node-3-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
      - 'ddc-node-2'
  ddc-node-4:
    container_name: 'ddc-node-4'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8084'
      - 'REMOTE_HTTP_ADDR=http://localhost:8084'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-4/tcp/5004'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8084:8084'
    volumes:
      - ./node-4-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
      - 'ddc-node-2'
      - 'ddc-node-3'
  ddc-node-5:
    container_name: 'ddc-node-5'
    image: '338287888375.dkr.ecr.us-west-2.amazonaws.com/ddc-node:v0.25.1-RC13'
    environment:
      - 'HTTP_PORT=8085'
      - 'REMOTE_HTTP_ADDR=http://localhost:8085'
      - 'P2P_LISTEN_ADDR=/dns4/ddc-node-5/tcp/5005'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'HEARTBEAT_INTERVAL_IN_SECONDS=1'
      - 'UPDATE_NEIGHBORS_INTERVAL_IN_SECONDS=1'
      - 'SHORT_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=4'
      - 'LONG_TRANSIENT_FAULT_TIMEOUT_IN_SECONDS=20'
      - 'COMPLETE_FAULT_TIMEOUT_IN_SECONDS=40'
      - 'PARTITIONS=27'
      - 'PARTITION_SIZE_LIMIT_IN_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_MODE=true'
      - 'DDC_MOCK_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
    ports:
      - '8085:8085'
    volumes:
      - ./node-5-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
      - 'ddc-node-2'
      - 'ddc-node-3'
      - 'ddc-node-4'
