version: '3'
services:
  ddc-node-0:
    container_name: 'ddc-node-0'
    image: 'cerebellumnetwork/ddc-node:v0.27.8'
    environment:
      - 'HTTP_PORT=8080'
      - 'HTTP_ADDRESS=http://localhost:8080'
      - 'P2P_ADDRESS=/dns4/ddc-node-0/tcp/5000'
      - 'P2P_WHITELIST=12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'FAULT_DETECTION_HEARTBEAT_INTERVAL=1s'
      - 'FAULT_DETECTION_UPDATE_NEIGHBORS_INTERVAL=1s'
      - 'FAULT_DETECTION_SHORT_TRANSIENT_FAULT_TIMEOUT=4s'
      - 'FAULT_DETECTION_LONG_TRANSIENT_FAULT_TIMEOUT=20s'
      - 'FAULT_DETECTION_COMPLETE_FAULT_TIMEOUT=40s'
      - 'TOTAL_PARTITIONS=45'
      - 'PARTITION_SIZE_LIMIT_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_ENABLED=true'
      - 'TEST_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'TEST_DDC_NODES=${TEST_DDC_NODES}'
    ports:
      - '8080:8080'
    volumes:
      - ./node-0-p2p-config.json:/config/p2p.json
  ddc-node-1:
    container_name: 'ddc-node-1'
    image: 'cerebellumnetwork/ddc-node:v0.27.8'
    environment:
      - 'HTTP_PORT=8081'
      - 'HTTP_ADDRESS=http://localhost:8081'
      - 'P2P_ADDRESS=/dns4/ddc-node-1/tcp/5001'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'FAULT_DETECTION_HEARTBEAT_INTERVAL=1s'
      - 'FAULT_DETECTION_UPDATE_NEIGHBORS_INTERVAL=1s'
      - 'FAULT_DETECTION_SHORT_TRANSIENT_FAULT_TIMEOUT=4s'
      - 'FAULT_DETECTION_LONG_TRANSIENT_FAULT_TIMEOUT=20s'
      - 'FAULT_DETECTION_COMPLETE_FAULT_TIMEOUT=40s'
      - 'TOTAL_PARTITIONS=45'
      - 'PARTITION_SIZE_LIMIT_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_ENABLED=true'
      - 'TEST_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'TEST_DDC_NODES=${TEST_DDC_NODES}'
    ports:
      - '8081:8081'
    volumes:
      - ./node-1-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
  ddc-node-2:
    container_name: 'ddc-node-2'
    image: 'cerebellumnetwork/ddc-node:v0.27.8'
    environment:
      - 'HTTP_PORT=8082'
      - 'HTTP_ADDRESS=http://localhost:8082'
      - 'P2P_ADDRESS=/dns4/ddc-node-2/tcp/5002'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'FAULT_DETECTION_HEARTBEAT_INTERVAL=1s'
      - 'FAULT_DETECTION_UPDATE_NEIGHBORS_INTERVAL=1s'
      - 'FAULT_DETECTION_SHORT_TRANSIENT_FAULT_TIMEOUT=4s'
      - 'FAULT_DETECTION_LONG_TRANSIENT_FAULT_TIMEOUT=20s'
      - 'FAULT_DETECTION_COMPLETE_FAULT_TIMEOUT=40s'
      - 'TOTAL_PARTITIONS=45'
      - 'PARTITION_SIZE_LIMIT_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_ENABLED=true'
      - 'TEST_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'TEST_DDC_NODES=${TEST_DDC_NODES}'
    ports:
      - '8082:8082'
    volumes:
      - ./node-2-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
  ddc-node-3:
    container_name: 'ddc-node-3'
    image: 'cerebellumnetwork/ddc-node:v0.27.8'
    environment:
      - 'HTTP_PORT=8083'
      - 'HTTP_ADDRESS=http://localhost:8083'
      - 'P2P_ADDRESS=/dns4/ddc-node-3/tcp/5003'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'FAULT_DETECTION_HEARTBEAT_INTERVAL=1s'
      - 'FAULT_DETECTION_UPDATE_NEIGHBORS_INTERVAL=1s'
      - 'FAULT_DETECTION_SHORT_TRANSIENT_FAULT_TIMEOUT=4s'
      - 'FAULT_DETECTION_LONG_TRANSIENT_FAULT_TIMEOUT=20s'
      - 'FAULT_DETECTION_COMPLETE_FAULT_TIMEOUT=40s'
      - 'TOTAL_PARTITIONS=45'
      - 'PARTITION_SIZE_LIMIT_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_ENABLED=true'
      - 'TEST_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'TEST_DDC_NODES=${TEST_DDC_NODES}'
    ports:
      - '8083:8083'
    volumes:
      - ./node-3-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
      - 'ddc-node-2'
  ddc-node-4:
    container_name: 'ddc-node-4'
    image: 'cerebellumnetwork/ddc-node:v0.27.8'
    environment:
      - 'HTTP_PORT=8084'
      - 'HTTP_ADDRESS=http://localhost:8084'
      - 'P2P_ADDRESS=/dns4/ddc-node-4/tcp/5004'
      - 'P2P_BOOTNODES=/dns4/ddc-node-0/tcp/5000/p2p/12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT'
      - 'P2P_WHITELIST=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWDfHbZfjJscBFxoHUefnUdAnJHkS95GEmWNZgBgsTTu6J'
      - 'TRUSTED_NODES=12D3KooWFRkkd4ycCPYEmeBzgfkrMrVSHWe6sYdgPo1JyAdLM4mT,12D3KooWJLuJEmtYf3bakUwe2q1uMcnbCBKRg7GkpG6Ws74Aq6NC,12D3KooWJ2h8af9sehgTKg6f2yPWYxLryVYbTAzpYQLLFp5GErxu,12D3KooWPfi9EtgoZHFnHh1at85mdZJtj7L8n94g6LFk6e8EEk2b,12D3KooWMDTP72eAEpTn34PCP4Pe1eKSMt7PbQGs2TsVYysXeuZf,12D3KooWQgWdrDD5gasMnWAxNhcmtxGm3ucXheNK9uzzw2dt2FhK,12D3KooWBTgBvQHbqRhMyERYr39h6YPK7iZHnVv12oJJhZLjuwBx'
      - 'LOG_LEVEL=debug'
      - 'FAULT_DETECTION_HEARTBEAT_INTERVAL=1s'
      - 'FAULT_DETECTION_UPDATE_NEIGHBORS_INTERVAL=1s'
      - 'FAULT_DETECTION_SHORT_TRANSIENT_FAULT_TIMEOUT=4s'
      - 'FAULT_DETECTION_LONG_TRANSIENT_FAULT_TIMEOUT=20s'
      - 'FAULT_DETECTION_COMPLETE_FAULT_TIMEOUT=40s'
      - 'TOTAL_PARTITIONS=45'
      - 'PARTITION_SIZE_LIMIT_BYTES=10000000'
      - 'PARTITION_WCU_LIMIT=180000000'
      - 'PARTITION_RCU_LIMIT=450000000'
      - 'TEST_ENABLED=true'
      - 'TEST_APP_LIMIT={"storageBytes":100000000,"wcu":90000000,"rcu":225000000}'
      - 'TEST_DDC_NODES=${TEST_DDC_NODES}'
    ports:
      - '8084:8084'
    volumes:
      - ./node-4-p2p-config.json:/config/p2p.json
    depends_on:
      - 'ddc-node-0'
      - 'ddc-node-1'
      - 'ddc-node-2'
      - 'ddc-node-3'
