name: CI-gradle-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: [self-hosted, cere-network-large-workers]
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: KengoTODA/actions-setup-docker-compose@main
        name: 'Install docker-compose'
        with:
          version: '1.29.2'
      - name: Cache build .gradle dir
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
      - name: Gradle Build
        timeout-minutes: 60
        run: ./gradlew build
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
